//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina.RecursosLocalizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResourcesEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResourcesEnglish() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nomina.RecursosLocalizables.StringResourcesEnglish", typeof(StringResourcesEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Mantenimiento.
        /// </summary>
        internal static string main1 {
            get {
                return ResourceManager.GetString("main1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Básicos.
        /// </summary>
        internal static string main2 {
            get {
                return ResourceManager.GetString("main2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepts.
        /// </summary>
        internal static string main3 {
            get {
                return ResourceManager.GetString("main3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Process.
        /// </summary>
        internal static string main4 {
            get {
                return ResourceManager.GetString("main4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.
        /// </summary>
        internal static string main5 {
            get {
                return ResourceManager.GetString("main5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string main6 {
            get {
                return ResourceManager.GetString("main6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Ficha del trabajador.
        /// </summary>
        internal static string sub_11 {
            get {
                return ResourceManager.GetString("sub_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Period.
        /// </summary>
        internal static string sub_12 {
            get {
                return ResourceManager.GetString("sub_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistencias.
        /// </summary>
        internal static string sub_14 {
            get {
                return ResourceManager.GetString("sub_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Civil.
        /// </summary>
        internal static string sub_21 {
            get {
                return ResourceManager.GetString("sub_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        internal static string sub_22 {
            get {
                return ResourceManager.GetString("sub_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string sub_23 {
            get {
                return ResourceManager.GetString("sub_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Department.
        /// </summary>
        internal static string sub_24 {
            get {
                return ResourceManager.GetString("sub_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concept.
        /// </summary>
        internal static string sub_31 {
            get {
                return ResourceManager.GetString("sub_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto por trabajador.
        /// </summary>
        internal static string sub_32 {
            get {
                return ResourceManager.GetString("sub_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto por periodo.
        /// </summary>
        internal static string sub_33 {
            get {
                return ResourceManager.GetString("sub_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto por tipo de nomina.
        /// </summary>
        internal static string sub_34 {
            get {
                return ResourceManager.GetString("sub_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Totales por recibo.
        /// </summary>
        internal static string sub_41 {
            get {
                return ResourceManager.GetString("sub_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar recibos (prenomina).
        /// </summary>
        internal static string sub_42 {
            get {
                return ResourceManager.GetString("sub_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar recibos (nomina).
        /// </summary>
        internal static string sub_43 {
            get {
                return ResourceManager.GetString("sub_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesos y perfiles.
        /// </summary>
        internal static string sub_51 {
            get {
                return ResourceManager.GetString("sub_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string sub_52 {
            get {
                return ResourceManager.GetString("sub_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permisos.
        /// </summary>
        internal static string sub_53 {
            get {
                return ResourceManager.GetString("sub_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración del sistema.
        /// </summary>
        internal static string sub_54 {
            get {
                return ResourceManager.GetString("sub_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asistentes.
        /// </summary>
        internal static string sub_61 {
            get {
                return ResourceManager.GetString("sub_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manuales.
        /// </summary>
        internal static string sub_62 {
            get {
                return ResourceManager.GetString("sub_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        internal static string sub_63 {
            get {
                return ResourceManager.GetString("sub_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nomina.
        /// </summary>
        internal static string titu1 {
            get {
                return ResourceManager.GetString("titu1", resourceCulture);
            }
        }
    }
}
